name: codia_demo_flutter
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  grouped_list: ^5.1.2
  bitsdojo_window: ^0.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/main_img.png
    - assets/bartender_point.png
    - assets/circle.png
    - assets/menu_selection.png
    - assets/normal1.png
    - assets/normal2.png
    - assets/normal3.png
    - assets/light.png
    - assets/selected.png
    - assets/june_bug.png
    - assets/jin_tonic.png
    - assets/moscow_mule.png
    - assets/screwdriver.png
    - assets/godfather.png
    - assets/Info_duotone_line.png
    - assets/lime.png
    - assets/light.png
    - assets/ice.png
    - assets/ginger_beer.png

